#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           LeftMotor,     tmotorVex393_HBridge, openLoop, reversed, encoderPort, dgtl3)
#pragma config(Motor,  port10,          RightMotor,    tmotorVex393_HBridge, openLoop, encoderPort, dgtl1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	clearDebugStream();
	motor[LeftMotor] = 127;
	motor[RightMotor] = 127;
	while(true){
		motor[LeftMotor] = 127;
		motor[RightMotor] = 127;
		writeDebugStreamLine("%i\t%i",SensorValue[leftEncoder],SensorValue[rightEncoder]);
		wait1Msec(20);
		}
}
