#pragma config(Sensor, dgtl1,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           RightMotor,    tmotorVex393_HBridge, openLoop, reversed, encoderPort, dgtl3)
#pragma config(Motor,  port10,          LeftMotor,     tmotorVex393_HBridge, openLoop, encoderPort, dgtl1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int errorLeft = 0, errorRight = 0;
int priorErrorLeft = 0, priorErrorRight = 0;

float KP = .5, bias = 25;

int iterationTime = 1;
int outputLeft = 0, outputRight = 0;
int pulses = 360, maxSpeed = 100;

task main(){
	clearDebugStream();
	for(int c=1; -(SensorValue[LeftEncoder])<= pulses || SensorValue[RightEncoder]<=pulses; c++){	//loop to run until encoders are equal or greater than 360
		//(run until one revolution completed)
		errorLeft = pulses - SensorValue[LeftEncoder];
		errorRight = pulses + SensorValue[RightEncoder];
		outputLeft = KP*errorLeft + bias;
		outputRight = KP*errorRight + bias;
		priorErrorLeft = errorLeft;
		priorErrorRight = errorRight;
		if(outputLeft > maxSpeed) outputLeft = maxSpeed; else if (outputLeft < -(maxSpeed)) outputLeft = -(maxSpeed);
		if(outputRight > maxSpeed) outputRight = maxSpeed; else if (outputRight < -(maxSpeed)) outputRight = -(maxSpeed);
		motor[LeftMotor] = outputLeft;	//move the left motor forward
		motor[RightMotor] = outputRight;	//move the right motor forward
		writeDebugStreamLine("%i\t%i",errorLeft,errorRight);
		wait1Msec(iterationTime);
		if (errorLeft<0 || errorRight<0)break;
	}
	writeDebugStreamLine("Finished!");
}
