#pragma config(Sensor, dgtl1,  RightQuadEncoder1, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LeftQuadEncoder1, sensorQuadEncoder)
#pragma config(Motor,  port1,           LeftMotor,     tmotorVex393_HBridge, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port10,          RightMotor,    tmotorVex393_HBridge, openLoop, encoderPort, dgtl1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	clearDebugStream();
	for(int c = 0; 1==1; c++){	//A loop to print the values into the debug stream
		writeDebugStreamLine("%i, %i",SensorValue[LeftQuadEncoder1],SensorValue[RightQuadEncoder1]); //Print the values into the debug stream
		wait1Msec(100);	//A timer to control the rate the values are printed
		//if(c>=10){	//Reset the encoder's value if a second has passed
			//c=0;	//Reset counter
			//SensorValue[RightQuadEncoder1] = 0;	//Reset the right encoder's values
			//SensorValue[LeftQuadEncoder1] = 0;	//Reset the left encoder's values
		//}
	}
}
